# ArchLinux image for otfmi module

FROM openturns/archlinux-module

# Install packages from AUR
RUN yay -Syu --noconfirm sundials-seq python-pyfmi python-pythonfmu python-fmpy-sundials6 openmodelica-omlibraries jdk-openjdk python-sphinxcontrib-bibtex python-sphinx-renku-theme
