name: Build
on:
  push:
  schedule:
    - cron: '0 0 * * 4'

jobs:
  archlinux-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: docker build archlinux-base -t openturns/archlinux-base
      - name: Upload
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: ./deploy.sh openturns/archlinux-base

  archlinux-python:
    needs: archlinux-base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: docker build archlinux-python -t openturns/archlinux-python
      - name: Upload
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: ./deploy.sh openturns/archlinux-python

  archlinux-mingw:
    needs: archlinux-base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: docker build archlinux-mingw -t openturns/archlinux-mingw
      - name: Upload
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: ./deploy.sh openturns/archlinux-mingw

  archlinux-module:
    needs: archlinux-base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: docker build archlinux-module -t openturns/archlinux-module
      - name: Upload
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: ./deploy.sh openturns/archlinux-module

  archlinux-module-mingw:
    needs: archlinux-mingw
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: docker build archlinux-module-mingw -t openturns/archlinux-module-mingw
      - name: Upload
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: ./deploy.sh openturns/archlinux-module-mingw

  manylinux2014_x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: docker build manylinux2014_x86_64 -t openturns/manylinux2014_x86_64
      - name: Test
        run: docker run --rm --volume `pwd`/manylinux2014_x86_64:/io openturns/manylinux2014_x86_64 sh -c "/io/run_docker_build.sh"
      - name: Upload
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: ./deploy.sh openturns/manylinux2014_x86_64

  debian-aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: docker build debian-aarch64 -t openturns/debian-aarch64
      - name: Upload
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: ./deploy.sh openturns/debian-aarch64

