name: Build
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 4'

jobs:
  archlinux-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build archlinux-base -t openturns/archlinux-base
      - name: Upload
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: ./deploy.sh openturns/archlinux-base

  archlinux-python:
    needs: archlinux-base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build archlinux-python -t openturns/archlinux-python
      - name: Upload
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: ./deploy.sh openturns/archlinux-python

  archlinux-mingw:
    needs: archlinux-base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build archlinux-mingw -t openturns/archlinux-mingw
      - name: Upload
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: ./deploy.sh openturns/archlinux-mingw

  archlinux-module:
    needs: archlinux-base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build archlinux-module -t openturns/archlinux-module
      - name: Upload
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: ./deploy.sh openturns/archlinux-module

  archlinux-module-mingw:
    needs: archlinux-base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build archlinux-module-mingw -t openturns/archlinux-module-mingw
      - name: Upload
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: ./deploy.sh openturns/archlinux-module-mingw

  manylinux1_x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build -t openturns/manylinux1_x86_64:latest manylinux1_x86_64
      - name: Upload
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: ./deploy.sh openturns/manylinux1_x86_64
