name: Build
on:
  push:
  schedule:
    - cron: '0 0 * * 4'

jobs:
  archlinux-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: docker build archlinux-base -t openturns/archlinux-base
      - name: Upload
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: ./deploy.sh openturns/archlinux-base

  archlinux-mingw:
    needs: archlinux-base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: docker build archlinux-mingw -t openturns/archlinux-mingw
      - name: Upload
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: ./deploy.sh openturns/archlinux-mingw

